# Specifying risk models for CanEpiRisk package


URL: <https://github.com/KyojiFurukawa/CanEpiRisk>

## Overview


A risk model used for risk calculations with **CanEpi** package may be a predefined model from either LSS mortality risk model object (\link{LSS_mortality}) or LSS cancer incidence model object (\link{LSS_mortality}). Otherwise, the user can specify any risk model by a list object with a certain format. As an example, the risk models derived from the INWORKS cohort for mortalities from all solid cancer (Richardson et al., 2015) and for leukaemia (Leuraud et al., 2015) can be specified as follows. Note that the uncertainty in the only risk model parameter (ERR/Gy) is specified by the 95% confidence interval, instead of the variance-covariance matrix in the LSS risk models objects.


## Example

````markdown
``` r
INWORKS_mortality <- NULL
INWORKS_mortality$allsolid <- NULL

INWORKS_mortality$allsolid$L <- list(
     err=list(
       para=c(0.47),                  # ERR/Gy=0.47 (90% CI: 0.18,0.79)  
       ci= c(0.1392403, 0.8521128),   #  95% CI coverted from 90%CI by Weibull approx.
       f=function (beta, data, lag=10) {
           beta[1] * data$dose  * (data$age - data$agex >= lag )
       }
       ),
      ear=list(    # dummry object
       para=c(4.8/10000),
       ci= c(0.1068428, 12.5703871)/10000,
       f=function (beta, data, lag=10) {
           beta[1] * data$dose  * (data$age - data$agex >= lag )
       } 
       )
 
  )

INWORKS_mortality$leukaemia$L <- list(
     err=list(
       para=c(2.96),                         # ERR/Gy=2.96 (90% CI: 1.17, 5.21) 
       ci= c(0.8664, 5.6940),
       f=function (beta, data, lag=2) {
           beta[1] * data$dose  * (data$age - data$agex >= lag )
       }
       ),
      ear=list(    # dummry object
       para=c(2.25/10000),
       var=NA,
       ci=c(0.5064054, 4.4914628)/10000,
       f=function (beta, data, lag=2) {
           beta[1] * data$dose  * (data$age - data$agex >= lag )
       } 
       )
  )

INWORKS_mortality



# Plotting solid cancer mortality risk, male, 
#          6.7(100/15)mGy at ages 30-45, followed up to age 60, LSS-L, LSS-LQ and INWORKS models

exp4 <- list( agex=30:44+0.5, doseGy=rep(0.1/15,15), sex=1 )   # Exposure scenario
opt4_err <- list( maxage=90, err_wgt=1 )    # for ERR transfer
opt4_ear <- list( maxage=90, err_wgt=0 )    # for EAR transfer

lss_err_L  <- Comp_Exrisk( exposure=exp4, riskmodel=LSS_mortality$allsolid$L,     option=opt4_err )
lss_err_LQ <- Comp_Exrisk( exposure=exp4, riskmodel=LSS_mortality$allsolid$LQ,    option=opt4_err )
inw_err_L  <- Comp_Exrisk( exposure=exp4, riskmodel=INWORKS_mortality$allsolid$L, option=opt4_err )

lss_ear_L  <- Comp_Exrisk( exposure=exp4, riskmodel=LSS_mortality$allsolid$L,     option=opt4_ear, per=10^4 )
lss_ear_LQ <- Comp_Exrisk( exposure=exp4, riskmodel=LSS_mortality$allsolid$LQ,    option=opt4_ear, per=10^4 )
inw_ear_L  <- Comp_Exrisk( exposure=exp4, riskmodel=INWORKS_mortality$allsolid$L, option=opt4_ear, per=10^4 )

par( mfrow=c(1,2) )
plot( c(30,90), c(0,0.1), type="n", ylab="Excess relative rate", xlab="age (years)" )
lines( lss_err_L, lty=2 )
lines( lss_err_LQ, lty=3 )
lines( inw_err_L )

plot( c(30,90), c(0,5), type="n", ylab="Excess absolute rate (cases per 10,000 person years)", xlab="age (years)" )
lines( lss_ear_L, lty=2 )
lines( lss_ear_LQ, lty=3 )
lines( inw_ear_L )


```
---



## Reference

Richardson, D.B., E. Cardis, R.D. Daniels et al. Risk of cancer from occupational exposure to ionising radiation: retrospective cohort study of workers in France, the United Kingdom, and the United States (INWORKS). BMJ 351: h5359 (2015).


Richardson, D.B., K. Leuraud, D. Laurier et al. Cancer mortality after low dose exposure to ionising radiation in workers in France, the United Kingdom, and the United States (INWORKS): cohort study. BMJ 382: e074520 (2023).






